// ─────────────────────────────────────────
//  百邑酒世界 · 全量 Mock 数据（扩充版）
// ─────────────────────────────────────────

export const MOCK_CATEGORIES = [
  { id: 'maotai',         name: '年份茅台',   icon: '🏺', slug: 'maotai',         color: '#C8A96E', hot: true  },
  { id: 'baijiu-sauce',   name: '酱香白酒',   icon: '🍶', slug: 'baijiu-sauce',   color: '#D4784A', hot: false },
  { id: 'baijiu-strong',  name: '浓香白酒',   icon: '🫙', slug: 'baijiu-strong',  color: '#8B6914', hot: false },
  { id: 'cognac',         name: '干邑白兰地', icon: '🍾', slug: 'cognac',         color: '#9C2935', hot: false },
  { id: 'whisky',         name: '威士忌',     icon: '🥃', slug: 'whisky',         color: '#8B4513', hot: true  },
  { id: 'red-wine',       name: '红葡萄酒',   icon: '🍷', slug: 'red-wine',       color: '#8B0000', hot: false },
  { id: 'vodka',          name: '伏特加',     icon: '🥂', slug: 'vodka',          color: '#4A90D9', hot: false },
  { id: 'sake',           name: '清酒',       icon: '🫙', slug: 'sake',           color: '#C8AD7F', hot: false },
  { id: 'beer-import',    name: '进口啤酒',   icon: '🍺', slug: 'beer-import',    color: '#D4820A', hot: false },
  { id: 'tea',            name: '茗茶茶具',   icon: '🫖', slug: 'tea',            color: '#27AE60', hot: false },
  { id: 'cigar',          name: '精品雪茄',   icon: '🚬', slug: 'cigar',          color: '#795548', hot: false },
  { id: 'gift',           name: '手信礼品',   icon: '🎁', slug: 'gift',           color: '#E91E8C', hot: false },
  { id: 'food',           name: '下酒好菜',   icon: '🥩', slug: 'food',           color: '#FF5722', hot: false },
  { id: 'flash-sale',     name: '特价促销',   icon: '🔥', slug: 'flash-sale',     color: '#F44336', hot: true  },
];

export const MOCK_ADS = [
  {
    id: 1,
    title: '年份个性化茅台',
    subtitle: '传世珍品，酱香典范，匠心酿造五十年',
    eyebrow: '镇店之宝',
    cta: '立即抢购',
    link: '/category/maotai',
    bg: 'linear-gradient(135deg, #1a0e00 0%, #3d2200 50%, #1a0e00 100%)',
    accentColor: 'rgba(200,169,110,0.45)',
  },
  {
    id: 2,
    title: '轩尼诗 XO 限时直降',
    subtitle: '法兰西顶级干邑，馥郁花香，丝滑绵长',
    eyebrow: '限时特惠',
    cta: '查看详情',
    link: '/category/cognac',
    bg: 'linear-gradient(135deg, #1a0505 0%, #4a0505 50%, #1a0505 100%)',
    accentColor: 'rgba(180,30,30,0.5)',
  },
  {
    id: 3,
    title: '百邑购物卡·区块链护航',
    subtitle: '零风险礼赠，链上存证，兑完即毁不留痕',
    eyebrow: '安全无忧',
    cta: '购卡查余额',
    link: '/card',
    bg: 'linear-gradient(135deg, #050520 0%, #0d1545 50%, #050520 100%)',
    accentColor: 'rgba(30,100,229,0.5)',
  },
  {
    id: 4,
    title: 'AI 直播间·品酒大师',
    subtitle: '每晚 20:00 准时开播，独家折扣实时抢购',
    eyebrow: '正在直播',
    cta: '进入直播间',
    link: '/live',
    bg: 'linear-gradient(135deg, #1a0530 0%, #35085a 50%, #1a0530 100%)',
    accentColor: 'rgba(142,36,170,0.55)',
  },
  {
    id: 5,
    title: '麦卡伦 18年 雪莉桶',
    subtitle: '苏格兰斯佩塞威士忌翘楚，干果可可绵密层次',
    eyebrow: '年度爆款',
    cta: '限时优惠',
    link: '/category/whisky',
    bg: 'linear-gradient(135deg, #1a0800 0%, #3d1500 50%, #1a0800 100%)',
    accentColor: 'rgba(180,100,20,0.5)',
  },
];

export const MOCK_PRODUCTS = [
  // ── 茅台 ───────────────────────────────────────────────────────
  {
    id: 'mt-2015-53',
    name: '贵州茅台 2015年 飞天',
    category: 'maotai', brand: '茅台',
    year: 2015, degree: 53,
    price: 2680, original_price: 3200,
    unit: '瓶/500ml', qr_prefix: 'MT201553',
    thumbnail: '/products/maotai-feitian.png',
    is_hot: true, is_new: false,
    rating: 5, reviews: 3821, sold_count: 520, stock: 38,
    tags: ['飞天陈年', '酱香收藏级', '有价无市'],
    tasting_notes: '酱香突出，幽雅细腻，酒体醇厚，回味悠长，空杯留香超60秒',
    ai_pairing: ['清蒸武昌鱼', '贵州腊肉', '豆腐乳'],
  },
  {
    id: 'mt-2021-53',
    name: '贵州茅台 2021年 飞天',
    category: 'maotai', brand: '茅台',
    year: 2021, degree: 53,
    price: 1499, original_price: 1799,
    unit: '瓶/500ml', qr_prefix: 'MT202153',
    thumbnail: '/products/maotai-feitian.png',
    is_hot: true, is_new: false,
    rating: 4.9, reviews: 2890, sold_count: 980, stock: 58,
    tags: ['经典飞天', '酱香', '宴请首选'],
    tasting_notes: '酱香正宗，入口柔顺，余韵绵长，是入门飞天的最佳选择',
    ai_pairing: ['粤式白切鸡', '清淡小菜', '生蚝'],
  },
  {
    id: 'mt-2018-53-jf',
    name: '贵州茅台 2018年 精飞',
    category: 'maotai', brand: '茅台',
    year: 2018, degree: 53,
    price: 1980, original_price: 2388,
    unit: '瓶/500ml', qr_prefix: 'MT201853',
    thumbnail: '/products/maotai-feitian.png',
    is_hot: false, is_new: false,
    rating: 5, reviews: 2076, sold_count: 420, stock: 45,
    tags: ['精品飞天', '酱香馥郁', '投资佳品'],
    tasting_notes: '酱香馥郁，陈香优雅，醇厚圆润，空杯留香持久悠扬',
    ai_pairing: ['鱼子酱', '黑松露菜肴', '清淡粤菜'],
  },
  {
    id: 'mt-2024-43',
    name: '贵州茅台 2024年 低度版',
    category: 'maotai', brand: '茅台',
    year: 2024, degree: 43,
    price: 1299, original_price: 1399,
    unit: '瓶/500ml', qr_prefix: 'MT202443',
    thumbnail: '/products/maotai-feitian.png',
    is_hot: false, is_new: true,
    rating: 4.7, reviews: 512, sold_count: 280, stock: 200,
    tags: ['低度入门', '花香宜人', '新品上市'],
    tasting_notes: '度数柔和，花香明显，易于入口，适合初次品味酱香的饮酒者',
    ai_pairing: ['海鲜沙拉', '水果拼盘', '轻食甜点'],
  },

  // ── 酱香白酒 ──────────────────────────────────────────────────
  {
    id: 'langjiu-honghuarlang-500',
    name: '郎酒·红花郎 10年',
    category: 'baijiu-sauce', brand: '郎酒',
    year: 2014, degree: 53,
    price: 328, original_price: 428,
    unit: '瓶/500ml', qr_prefix: 'LJ201453',
    is_hot: false, is_new: true,
    rating: 4.6, reviews: 2140, sold_count: 680, stock: 120,
    tags: ['酱香典雅', '性价比高', '宴请佳选'],
    tasting_notes: '红樱桃花香，入口绵柔，酱香幽雅，回味舒适持久',
    ai_pairing: ['红烧肉', '卤猪蹄', '酸笋炒肉'],
  },
  {
    id: 'jinmendao-baijiu-2018',
    name: '金门高粱酒 1992限定',
    category: 'baijiu-sauce', brand: '金门',
    year: 1992, degree: 58,
    price: 1280, original_price: 1680,
    unit: '瓶/600ml', qr_prefix: 'JM199258',
    is_hot: false, is_new: false,
    rating: 4.8, reviews: 318, sold_count: 95, stock: 15,
    tags: ['1992绝版', '粮香清雅', '台湾精品'],
    tasting_notes: '粮香清雅，入口辛辣回甘，余韵持久，是品鉴台湾高粱的上选',
    ai_pairing: ['凤梨酥', '烤肉串', '台式卤猪脚'],
  },
  {
    id: 'wuliangye-pujin-2024',
    name: '五粮液 普金 2024年',
    category: 'baijiu-strong', brand: '五粮液',
    year: 2024, degree: 52,
    price: 889, original_price: 1099,
    unit: '瓶/500ml', qr_prefix: 'WLY202452',
    is_hot: false, is_new: true,
    rating: 4.7, reviews: 782, sold_count: 290, stock: 150,
    tags: ['浓香醇厚', '五粮精酿', '新品上市'],
    tasting_notes: '浓香醇厚，粮香丰富，陈香悠长，口感绵甜，回味干净',
    ai_pairing: ['川式麻辣火锅', '宫保鸡丁', '粉蒸肉'],
  },

  // ── 干邑 ──────────────────────────────────────────────────────
  {
    id: 'hennessy-xo-700',
    name: '轩尼诗 XO 700ml',
    category: 'cognac', brand: '轩尼诗',
    year: 0, degree: 40,
    price: 1560, original_price: 2100,
    unit: '瓶/700ml', qr_prefix: 'HXO700',
    is_hot: true, is_new: false,
    rating: 4.9, reviews: 2104, sold_count: 380, stock: 55,
    tags: ['XO经典', '礼品首选', '法国进口'],
    tasting_notes: '馥郁花香，丰满圆润，橡木与香草气息缓缓展开，余韵如丝绸般顺滑',
    ai_pairing: ['黑巧克力', '奶酪拼盘', '鹅肝酱'],
  },
  {
    id: 'ct-blue-star-2023',
    name: '轩尼诗 VSOP 特酿',
    category: 'cognac', brand: '轩尼诗',
    year: 0, degree: 40,
    price: 568, original_price: 720,
    unit: '瓶/700ml', qr_prefix: 'HVSOP',
    is_hot: false, is_new: false,
    rating: 4.5, reviews: 1503, sold_count: 720, stock: 210,
    tags: ['VSOP入门', '性价比高', '调酒佳品'],
    tasting_notes: '香草橡木，烤糖蜜香，细腻平衡，是入门干邑的经典之选',
    ai_pairing: ['冰激凌', '焦糖布丁', '干果拼盘'],
  },
  {
    id: 'remy-martin-xo',
    name: '人头马 XO 卓越干邑',
    category: 'cognac', brand: '人头马',
    year: 0, degree: 40,
    price: 1380, original_price: 1680,
    unit: '瓶/700ml', qr_prefix: 'RMXO700',
    is_hot: false, is_new: false,
    rating: 4.8, reviews: 1201, sold_count: 260, stock: 40,
    tags: ['百年老厂', '大香槟区', '卓越品质'],
    tasting_notes: '圆润顺滑，干花、蜂蜜、李子与橡木交织，层次丰富，余韵悠长',
    ai_pairing: ['蓝纹奶酪', '核桃仁', '黑松露'],
  },

  // ── 威士忌 ────────────────────────────────────────────────────
  {
    id: 'macallan-18-sherry',
    name: '麦卡伦 18年 雪莉桶',
    category: 'whisky', brand: '麦卡伦',
    year: 18, degree: 43,
    price: 3280, original_price: 4200,
    unit: '瓶/700ml', qr_prefix: 'MC18SH',
    is_hot: true, is_new: false,
    rating: 5, reviews: 1892, sold_count: 210, stock: 22,
    tags: ['18年陈酿', '雪莉桶', '苏格兰之王'],
    tasting_notes: '饱满干果、黑巧克力、橡木香辛，层次丰富，余韵悠长绵密',
    ai_pairing: ['蓝纹奶酪', '烟熏三文鱼', '黑巧克力'],
  },
  {
    id: 'glenfiddich-15-solera',
    name: '格兰菲迪 15年 索雷拉',
    category: 'whisky', brand: '格兰菲迪',
    year: 15, degree: 40,
    price: 680, original_price: 880,
    unit: '瓶/700ml', qr_prefix: 'GF15SL',
    is_hot: false, is_new: true,
    rating: 4.5, reviews: 654, sold_count: 180, stock: 66,
    tags: ['索雷拉桶', '奶油风味', '入门首选'],
    tasting_notes: '奶油香草，成熟果实，雪莉甜蜜，余韵温暖，适合初尝斯佩塞风格',
    ai_pairing: ['提拉米苏', '蜂蜜蛋糕', '干果巧克力'],
  },
  {
    id: 'chivas-regal-18',
    name: '芝华士 18年 金玺',
    category: 'whisky', brand: '芝华士',
    year: 18, degree: 40,
    price: 480, original_price: 620,
    unit: '瓶/700ml', qr_prefix: 'CR18',
    is_hot: false, is_new: false,
    rating: 4.4, reviews: 2231, sold_count: 880, stock: 320,
    tags: ['调和威士忌', '大众熟知', '宴请定番'],
    tasting_notes: '蜂蜜黑巧克力，烤坚果，奶油柔滑，尾段温暖，适合宴请场合',
    ai_pairing: ['烟熏肉', '苹果派', '焦糖布丁'],
  },
  {
    id: 'laphroaig-10',
    name: '拉弗格 10年 艾雷岛单一麦芽',
    category: 'whisky', brand: '拉弗格',
    year: 10, degree: 43,
    price: 520, original_price: 680,
    unit: '瓶/700ml', qr_prefix: 'LF10IS',
    is_hot: false, is_new: false,
    rating: 4.6, reviews: 876, sold_count: 340, stock: 88,
    tags: ['艾雷岛泥煤', '正宗烟熏', '个性化'],
    tasting_notes: '强烈碘味与泥煤烟熏，夹杂海盐柠檬气息，极具个性，令人难忘',
    ai_pairing: ['生蚝', '烟熏三文鱼', '黑胡椒牛排'],
  },

  // ── 红葡萄酒 ──────────────────────────────────────────────────
  {
    id: 'lafite-zhuanbao-2020',
    name: '拉菲珍宝 2020',
    category: 'red-wine', brand: '拉菲',
    year: 2020, degree: 13,
    price: 680, original_price: 888,
    unit: '瓶/750ml', qr_prefix: 'LFZB2020',
    is_hot: true, is_new: false,
    rating: 4.7, reviews: 956, sold_count: 340, stock: 80,
    tags: ['拉菲系列', '波尔多产区', '日常餐酒'],
    tasting_notes: '黑醋栗、雪松香气，单宁丝滑，果香充沛，是波尔多入门佳作',
    ai_pairing: ['战斧牛排', '羊排', '蘑菇意大利面'],
  },
  {
    id: 'mouton-2019',
    name: '木桐庄园 2019年',
    category: 'red-wine', brand: '木桐',
    year: 2019, degree: 14,
    price: 2180, original_price: 2800,
    unit: '瓶/750ml', qr_prefix: 'MT2019WE',
    is_hot: false, is_new: true,
    rating: 5, reviews: 412, sold_count: 88, stock: 20,
    tags: ['一级名庄', '97分', '可窖藏30年'],
    tasting_notes: '黑浆果、铅笔芯、玫瑰花瓣，单宁成熟精致，结构宏大壮丽',
    ai_pairing: ['红烩羊腿', '黑松露牛排', '成熟奶酪'],
  },
  {
    id: 'lafite-2019',
    name: '拉菲古堡正牌 2019年',
    category: 'red-wine', brand: '拉菲',
    year: 2019, degree: 13.5,
    price: 5800, original_price: 6500,
    unit: '瓶/750ml', qr_prefix: 'LF2019',
    is_hot: false, is_new: false,
    rating: 5, reviews: 289, sold_count: 55, stock: 6,
    tags: ['一级名庄', '波尔多正牌', '收藏级投资'],
    tasting_notes: '黑醋栗、雪松木香气层叠，结构宏大精密，可窖藏30年以上',
    ai_pairing: ['战斧牛排', '羊腿', '黑松露'],
  },

  // ── 伏特加 ────────────────────────────────────────────────────
  {
    id: 'smirnoff-gold',
    name: '皇冠伏特加 金装限定',
    category: 'vodka', brand: '皇冠',
    year: 2024, degree: 40,
    price: 289, original_price: 350,
    unit: '瓶/750ml', qr_prefix: 'SG2024',
    is_hot: false, is_new: true,
    rating: 4.4, reviews: 876, sold_count: 420, stock: 180,
    tags: ['金装限定', '纯粮蒸馏', '调酒首选'],
    tasting_notes: '晶莹纯净，入口极为柔和，无异味，适合纯饮或调制各类鸡尾酒',
    ai_pairing: ['鱼子酱', '腌三文鱼', '薯片小食'],
  },
  {
    id: 'absolut-elyx',
    name: '绝对伏特加 超级单一麦芽',
    category: 'vodka', brand: '绝对',
    year: 2023, degree: 42,
    price: 420, original_price: 560,
    unit: '瓶/700ml', qr_prefix: 'AE2023',
    is_hot: false, is_new: false,
    rating: 4.6, reviews: 542, sold_count: 195, stock: 65,
    tags: ['铜蒸馏', '手工精酿', '顶级品质'],
    tasting_notes: '柔滑奶油质地，淡淡谷物香气，回味干净悠长，纯饮最佳',
    ai_pairing: ['牡蛎', '柠檬慕斯', '北欧冷菜'],
  },

  // ── 清酒 ──────────────────────────────────────────────────────
  {
    id: 'dassai-junmai-daiginjo',
    name: '獭祭 纯米大吟酿 39',
    category: 'sake', brand: '旭酒造',
    year: 2024, degree: 16,
    price: 380, original_price: 480,
    unit: '瓶/720ml', qr_prefix: 'DS3924',
    is_hot: false, is_new: false,
    rating: 4.8, reviews: 1024, sold_count: 380, stock: 90,
    tags: ['纯米大吟酿', '精米39%', '日本清酒翘楚'],
    tasting_notes: '花香果香馥郁，清雅细腻，甘甜辛口平衡，是日本清酒的顶级代表',
    ai_pairing: ['刺身拼盘', '清蒸螃蟹', '豆腐料理'],
  },
  {
    id: 'kubota-manju',
    name: '久保田 万寿 无过滤',
    category: 'sake', brand: '朝日酒造',
    year: 2023, degree: 15,
    price: 520, original_price: 650,
    unit: '瓶/720ml', qr_prefix: 'KM2023',
    is_hot: false, is_new: false,
    rating: 4.7, reviews: 632, sold_count: 220, stock: 45,
    tags: ['无过滤', '原酒味道', '稀有限定'],
    tasting_notes: '米香浓郁，酒体饱满，原酒风味完整呈现，适合搭配浓郁料理',
    ai_pairing: ['烤和牛', '味噌汤', '炸猪排'],
  },

  // ── 进口啤酒 ──────────────────────────────────────────────────
  {
    id: 'chimay-blue',
    name: '智美 蓝帽 修道院啤酒',
    category: 'beer-import', brand: '智美',
    year: 2024, degree: 9,
    price: 58, original_price: 72,
    unit: '瓶/330ml', qr_prefix: 'CHBLUE',
    is_hot: false, is_new: false,
    rating: 4.8, reviews: 1563, sold_count: 2800, stock: 500,
    tags: ['修道院精酿', '比利时进口', '高度啤酒'],
    tasting_notes: '深邃果香，麦芽焦糖，丁香香料，尾段微苦而悠长，是精酿世界的巅峰',
    ai_pairing: ['炖牛尾', '野猪肉', '硬质奶酪'],
  },
  {
    id: 'weihenstephan-alkomas',
    name: '维恩斯蒂芬 白啤 500ml',
    category: 'beer-import', brand: '维恩斯蒂芬',
    year: 2024, degree: 5.4,
    price: 35, original_price: 45,
    unit: '瓶/500ml', qr_prefix: 'WS2024',
    is_hot: false, is_new: false,
    rating: 4.6, reviews: 2145, sold_count: 5200, stock: 800,
    tags: ['世界最古老酒厂', '德国小麦白啤', '浑浊酵母'],
    tasting_notes: '香蕉丁香泡泡糖香气，口感醇厚绵密，泡沫丰富持久',
    ai_pairing: ['德式猪肘', '椒盐脆薯', '白香肠'],
  },

  // ── 茗茶 ──────────────────────────────────────────────────────
  {
    id: 'dahongpao-gift',
    name: '武夷山大红袍 · 百邑臻品礼盒',
    category: 'tea', brand: '百邑茶叶',
    year: 2024, degree: 0,
    price: 1280, original_price: 1680,
    unit: '套/200g + 茶具', qr_prefix: 'DHP2024',
    is_hot: false, is_new: false,
    rating: 4.9, reviews: 342, sold_count: 168, stock: 55,
    tags: ['岩骨花香', '精品茶具套装', '商务礼品'],
    tasting_notes: '岩韵明显，兰香持久，汤色金黄透亮，岩骨之感令人回味',
    ai_pairing: ['茶点', '坚果', '清淡糕点'],
  },
  {
    id: 'biluochun-2024',
    name: '洞庭碧螺春 · 特级',
    category: 'tea', brand: '苏州茶厂',
    year: 2024, degree: 0,
    price: 380, original_price: 480,
    unit: '盒/100g', qr_prefix: 'BLC2024',
    is_hot: false, is_new: true,
    rating: 4.7, reviews: 528, sold_count: 290, stock: 120,
    tags: ['明前春茶', '特级绿茶', '花果香'],
    tasting_notes: '嫩绿鲜爽，毫香蜜韵，清甜回甘，是绿茶中的上品',
    ai_pairing: ['清淡点心', '坚果', '新鲜水果'],
  },

  // ── 雪茄 ──────────────────────────────────────────────────────
  {
    id: 'cohiba-siglo',
    name: '高希霸 世纪六号 古巴雪茄',
    category: 'cigar', brand: '高希霸',
    year: 2023, degree: 0,
    price: 1800, original_price: 2200,
    unit: '支/单支', qr_prefix: 'CHS2023',
    is_hot: true, is_new: false,
    rating: 5, reviews: 156, sold_count: 89, stock: 24,
    tags: ['古巴国宝', '至尊系列', '限量珍藏'],
    tasting_notes: '奶油、坚果与雪松香气交融，烟灰洁白细腻，燃烧均匀优雅',
    ai_pairing: ['威士忌', '干邑白兰地', '浓缩咖啡'],
  },
  {
    id: 'montecristo-4',
    name: '蒙特克里斯托 4号 古巴雪茄',
    category: 'cigar', brand: '蒙特',
    year: 2023, degree: 0,
    price: 320, original_price: 420,
    unit: '支/单支', qr_prefix: 'MC42023',
    is_hot: false, is_new: false,
    rating: 4.7, reviews: 289, sold_count: 245, stock: 60,
    tags: ['中等烟力', '均衡经典', '入门雪茄'],
    tasting_notes: '木质、坚果、咖啡的和谐组合，烟力适中，是入门古巴雪茄的理想选择',
    ai_pairing: ['干邑白兰地', '浓缩咖啡', '黑巧克力'],
  },

  // ── 礼品 ──────────────────────────────────────────────────────
  {
    id: 'gift-maotai-box',
    name: '贵州茅台节日礼盒 · 双瓶装',
    category: 'gift', brand: '茅台',
    year: 2023, degree: 53,
    price: 3200, original_price: 3800,
    unit: '盒/2×500ml', qr_prefix: 'MTGIFT',
    is_hot: false, is_new: false,
    rating: 4.9, reviews: 622, sold_count: 180, stock: 30,
    tags: ['节日礼盒', '双瓶套装', '高端送礼'],
    tasting_notes: '飞天经典酱香，双瓶装隆重正式，精美礼盒适合各种节庆场合',
    ai_pairing: ['商务宴请', '节日馈赠', '收藏投资'],
  },

  // ── 下酒菜 ────────────────────────────────────────────────────
  {
    id: 'food-hairy-crab',
    name: '阳澄湖大闸蟹 · 礼盒装',
    category: 'food', brand: '阳澄湖蟹业',
    year: 2024, degree: 0,
    price: 880, original_price: 1200,
    unit: '盒/公3.5两×4+母2.5两×4',
    qr_prefix: 'DLHC2024',
    is_hot: false, is_new: false,
    rating: 4.8, reviews: 1823, sold_count: 620, stock: 80,
    tags: ['阳澄湖', '礼盒装', '现发活蟹'],
    tasting_notes: '蟹膏饱满，鲜甜醇厚，搭配茅台享受极致秋蟹体验',
    ai_pairing: ['茅台飞天', '黄酒', '姜茶'],
  },
  {
    id: 'food-iberico-ham',
    name: '西班牙伊比利亚火腿 · 切片装',
    category: 'food', brand: 'Jamón',
    year: 2023, degree: 0,
    price: 480, original_price: 620,
    unit: '盒/100g切片装', qr_prefix: 'IBHAM',
    is_hot: false, is_new: false,
    rating: 4.7, reviews: 342, sold_count: 180, stock: 60,
    tags: ['伊比利亚猪', '72个月熟成', '配红酒最佳'],
    tasting_notes: '入口即化，坚果油脂香气绵延，是配合葡萄酒的顶级佐餐',
    ai_pairing: ['拉菲正牌', '里奥哈红酒', '曼萨尼亚雪利'],
  },

  // ── 补品 ──────────────────────────────────────────────────────
  {
    id: 'luyong-gift-box',
    name: '长白山鹿茸·臻品礼盒',
    category: 'supplement', brand: '长白山参茸',
    year: 2024, degree: 0,
    price: 1680, original_price: 2280,
    unit: '盒/鹿茸片50g + 礼盒', qr_prefix: 'LY2024',
    is_hot: true, is_new: false,
    rating: 4.8, reviews: 562, sold_count: 280, stock: 60,
    tags: ['吉林长白山', '鲜切冻干', '滋补上品'],
    tasting_notes: '鹿茸片色泽栗黄，质地细腻，搭配白酒浸泡或直接口含，滋补效果显著',
    ai_pairing: ['茅台年份酒浸泡', '蜂蜜冲服', '枸杞煮汤'],
  },
  {
    id: 'american-ginseng-slice',
    name: '美国西洋参·切片装',
    category: 'supplement', brand: '花旗参',
    year: 2024, degree: 0,
    price: 480, original_price: 680,
    unit: '盒/100g切片', qr_prefix: 'WY2024',
    is_hot: false, is_new: true,
    rating: 4.7, reviews: 328, sold_count: 180, stock: 120,
    tags: ['美国原装进口', '生津止渴', '清补佳品'],
    tasting_notes: '参香清雅，甘凉微苦，适合煮汤、泡茶或直接含服，是夏季清补首选',
    ai_pairing: ['清水煮服', '石斛泡茶', '蜂蜜水冲服'],
  },

  // ── 手信 ──────────────────────────────────────────────────────
  {
    id: 'maotai-mini-gift',
    name: '茅台镇酱酒·迷你手信礼盒（6瓶装）',
    category: 'gift', brand: '茅台镇名酿',
    year: 2024, degree: 53,
    price: 388, original_price: 498,
    unit: '盒/6×100ml', qr_prefix: 'MTMINI',
    is_hot: true, is_new: false,
    rating: 4.8, reviews: 892, sold_count: 1280, stock: 350,
    tags: ['迷你手信', '出行携带', '伴手礼首选'],
    tasting_notes: '纯粮酿造，酱香馥郁，小瓶装方便携带，是走亲访友、商务伴手礼的热门之选',
    ai_pairing: ['搭配任何佳肴', '商务会面', '节日馈赠'],
  },
  {
    id: 'premium-souvenir-set',
    name: '百邑名酒伴手礼精选套装',
    category: 'gift', brand: '百邑酒世界',
    year: 2024, degree: 0,
    price: 688, original_price: 880,
    unit: '套/4款各1支×50ml', qr_prefix: 'BYSH2024',
    is_hot: false, is_new: true,
    rating: 4.9, reviews: 456, sold_count: 560, stock: 200,
    tags: ['四款精选', '品鉴入门', '出境旅游首选'],
    tasting_notes: '茅台酱香、五粮浓香、麦卡伦威士忌、轩尼诗白兰地，一盒品味四种风格',
    ai_pairing: ['出行旅游', '商务会面', '品鉴活动'],
  },

  // ── 零食 ──────────────────────────────────────────────────────
  {
    id: 'xinjiang-nuts-gift',
    name: '新疆坚果大礼包·每日坚果系列',
    category: 'snack', brand: '三只松鼠',
    year: 2024, degree: 0,
    price: 128, original_price: 168,
    unit: '箱/30包×30g', qr_prefix: 'NUT2024',
    is_hot: false, is_new: false,
    rating: 4.6, reviews: 3420, sold_count: 8600, stock: 1200,
    tags: ['新疆原产', '混合坚果', '配酒下酒首选'],
    tasting_notes: '核桃、杏仁、腰果、蔓越莓混合，与威士忌、葡萄酒搭配绝佳，是品酒宴席的理想小食',
    ai_pairing: ['麦卡伦威士忌', '拉菲红酒', '清酒宴席'],
  },
  {
    id: 'jiuxia-snack-platter',
    name: '下酒小食拼盘·臻品精选',
    category: 'snack', brand: '百邑食品',
    year: 2024, degree: 0,
    price: 238, original_price: 298,
    unit: '盒/8款精选共400g', qr_prefix: 'JX2024',
    is_hot: true, is_new: false,
    rating: 4.7, reviews: 1890, sold_count: 3200, stock: 500,
    tags: ['8款精选', '即食方便', '宴席必备'],
    tasting_notes: '牛肉干、鱿鱼丝、夏威夷果、腰果仁、豆干、花生等，精选8款配酒小食，宴席聚会必备',
    ai_pairing: ['白酒宴席', '啤酒聚会', '葡萄酒派对'],
  },

  // ── 饮品 ──────────────────────────────────────────────────────
  {
    id: 'mineral-water-nongfu',
    name: '农夫山泉·天然矿泉水（配酒专用）',
    category: 'drinks', brand: '农夫山泉',
    year: 2024, degree: 0,
    price: 38, original_price: 48,
    unit: '箱/24瓶×380ml', qr_prefix: 'NFS2024',
    is_hot: false, is_new: false,
    rating: 4.5, reviews: 12800, sold_count: 88000, stock: 5000,
    tags: ['配酒必备', '天然水源', '软水护胃'],
    tasting_notes: '天然矿泉，口感甘甜，低矿化度，是威士忌、白兰地的最佳配水，保护胃黏膜效果好',
    ai_pairing: ['威士忌配水', '白酒护胃', '解酒必备'],
  },
  {
    id: 'cocktail-mixer-set',
    name: '鸡尾酒调配原浆·6味精选',
    category: 'drinks', brand: '百邑调酒',
    year: 2024, degree: 0,
    price: 198, original_price: 268,
    unit: '套/6瓶×250ml', qr_prefix: 'CM2024',
    is_hot: false, is_new: true,
    rating: 4.6, reviews: 734, sold_count: 980, stock: 300,
    tags: ['6种口味', '居家调酒', '派对首选'],
    tasting_notes: '蔓越莓、柠檬、青柠、桃子、西瓜、百香果6款风味，搭配伏特加或白酒，轻松调出精品鸡尾酒',
    ai_pairing: ['皇冠伏特加', '绝对伏特加', '金酒'],
  },

  // ── 扑克 ──────────────────────────────────────────────────────
  {
    id: 'maotai-poker-limited',
    name: '茅台主题·限定版扑克牌',
    category: 'poker', brand: '百邑文创',
    year: 2024, degree: 0,
    price: 28, original_price: 45,
    unit: '套/2副装', qr_prefix: 'PK2024MT',
    is_hot: false, is_new: true,
    rating: 4.7, reviews: 328, sold_count: 1560, stock: 800,
    tags: ['茅台主题', '限定版', '收藏+实用'],
    tasting_notes: '以茅台飞天、五粮液、轩尼诗等名酒为主题设计，每张牌面精美印刷，是收藏和宴会娱乐的双重之选',
    ai_pairing: ['茅台宴会', '朋友聚会', '商务礼品'],
  },
  {
    id: 'baijiu-poker-deluxe',
    name: '百邑酒世界·名酒文化扑克礼盒',
    category: 'poker', brand: '百邑文创',
    year: 2024, degree: 0,
    price: 45, original_price: 68,
    unit: '盒/精装礼盒双副', qr_prefix: 'PK2024BY',
    is_hot: false, is_new: false,
    rating: 4.6, reviews: 212, sold_count: 680, stock: 400,
    tags: ['文化礼盒', '酒文化图案', '送礼佳品'],
    tasting_notes: '融合中国酒文化元素，精选54张设计感十足的图案，外配精装礼盒，是宴会助兴、商务赠礼的精品之选',
    ai_pairing: ['商务宴席', '亲友聚会', '节日礼品'],
  },

  // ── 利口酒 ────────────────────────────────────────────────────
  {
    id: 'baileys-original',
    name: '百利甜酒 原味奶油利口酒',
    category: 'liqueur', brand: '百利',
    year: 2024, degree: 17,
    price: 128, original_price: 168,
    unit: '瓶/700ml', qr_prefix: 'BAIL700',
    is_hot: true, is_new: false,
    rating: 4.7, reviews: 4320, sold_count: 12000, stock: 800,
    tags: ['奶油利口酒', '入门首选', '咖啡调酒'],
    tasting_notes: '浓郁奶油与爱尔兰威士忌融合，口感丝滑甜蜜，搭配咖啡或冰淇淋享用绝佳',
    ai_pairing: ['咖啡拿铁', '冰淇淋', '提拉米苏'],
  },
  {
    id: 'cointreau-triple-sec',
    name: '君度橙皮利口酒 40°',
    category: 'liqueur', brand: '君度',
    year: 2024, degree: 40,
    price: 188, original_price: 238,
    unit: '瓶/700ml', qr_prefix: 'CT700',
    is_hot: false, is_new: false,
    rating: 4.6, reviews: 2180, sold_count: 3800, stock: 300,
    tags: ['橙皮精华', '调酒经典', '法国进口'],
    tasting_notes: '甜橙与苦橙皮精华，清爽花香，是调制玛格丽特、柯斯莫的经典原料',
    ai_pairing: ['玛格丽特调酒', '蓝莓酱', '橙子甜点'],
  },

  // ── 精酿啤酒 ──────────────────────────────────────────────────
  {
    id: 'goose-island-ipa',
    name: '鹅岛 IPA 印度淡色艾尔',
    category: 'craft-beer', brand: '鹅岛',
    year: 2024, degree: 5.9,
    price: 32, original_price: 42,
    unit: '瓶/355ml', qr_prefix: 'GI355',
    is_hot: true, is_new: false,
    rating: 4.6, reviews: 3240, sold_count: 15000, stock: 1200,
    tags: ['美国精酿', 'IPA苦香', '啤酒花馥郁'],
    tasting_notes: '热带水果与啤酒花香气交织，苦感适中清爽，余味悠长，是IPA入门的经典之选',
    ai_pairing: ['辣翅', '炸鱼薯条', '墨西哥玉米饼'],
  },
  {
    id: 'brooklyn-lager',
    name: '布鲁克林 拉格精酿啤酒',
    category: 'craft-beer', brand: '布鲁克林',
    year: 2024, degree: 5.2,
    price: 28, original_price: 38,
    unit: '瓶/355ml', qr_prefix: 'BK355',
    is_hot: false, is_new: false,
    rating: 4.5, reviews: 2890, sold_count: 9800, stock: 1500,
    tags: ['纽约精酿', '麦芽甘甜', '日常饮用'],
    tasting_notes: '麦芽甘甜，花香清爽，色泽金黄透亮，是日常饮用精酿的绝佳选择',
    ai_pairing: ['汉堡', '烤肠', '沙拉'],
  },

  // ── 礼品卡 ────────────────────────────────────────────────────
  {
    id: 'gift-card-500',
    name: '百邑酒世界 电子礼品卡 500元面值',
    category: 'gift-card', brand: '百邑酒世界',
    year: 2024, degree: 0,
    price: 500, original_price: 500,
    unit: '张/电子卡', qr_prefix: 'GC500',
    is_hot: false, is_new: false,
    rating: 5.0, reviews: 1820, sold_count: 4200, stock: 99999,
    tags: ['即时到账', '全场通用', '节日首选'],
    tasting_notes: '全场商品通用，即时到账，有效期3年，支持分次使用，是送礼最省心的选择',
    ai_pairing: ['商务礼赠', '节日送礼', '员工福利'],
  },
  {
    id: 'gift-card-1000',
    name: '百邑酒世界 电子礼品卡 1000元面值',
    category: 'gift-card', brand: '百邑酒世界',
    year: 2024, degree: 0,
    price: 1000, original_price: 1000,
    unit: '张/电子卡', qr_prefix: 'GC1000',
    is_hot: true, is_new: false,
    rating: 5.0, reviews: 2650, sold_count: 8800, stock: 99999,
    tags: ['千元大额', '全场通用', '企业团购'],
    tasting_notes: '全场商品通用，支持拆分使用，有效期3年，企业团购可享额外优惠',
    ai_pairing: ['企业团购', '高端礼赠', '年节福利'],
  },

  // ── 更多茅台 ──
  { id:'mt-zodiac-dragon', name:'贵州茅台 2024龙年生肖纪念酒', category:'maotai', brand:'茅台', year:2024, degree:53, price:2800, original_price:3200, unit:'瓶/500ml', qr_prefix:'MTDR24', is_hot:true, is_new:true, rating:5.0, reviews:1230, sold_count:320, stock:18, tags:['龙年限定','生肖系列','收藏级'], tasting_notes:'龙年生肖纪念版，酱香突出，陈香幽雅，限量发行极具收藏价值', ai_pairing:['商务宴请','节日赠礼','收藏投资'] },
  { id:'mt-prince-500', name:'茅台王子酒 酱香型 500ml', category:'maotai', brand:'茅台', year:2024, degree:53, price:198, original_price:238, unit:'瓶/500ml', qr_prefix:'MTPRC', is_hot:false, is_new:false, rating:4.5, reviews:5600, sold_count:8900, stock:500, tags:['入门茅系','性价比高','日常宴请'], tasting_notes:'茅台旗下经典产品，酱香纯正，口感绵柔，是茅系入门首选', ai_pairing:['家常小炒','朋友聚餐','商务便宴'] },
  { id:'mt-yingbin-500', name:'茅台迎宾酒 酱香型', category:'maotai', brand:'茅台', year:2024, degree:53, price:128, original_price:158, unit:'瓶/500ml', qr_prefix:'MTYB', is_hot:false, is_new:false, rating:4.4, reviews:3200, sold_count:12000, stock:800, tags:['大众茅系','口粮酒','高性价比'], tasting_notes:'酱香清雅，入口顺滑，是日常口粮级茅系酱香酒首选', ai_pairing:['家庭聚餐','朋友小聚','日常小酌'] },
  { id:'mt-1935', name:'茅台1935 酱香型白酒', category:'maotai', brand:'茅台', year:2022, degree:53, price:1050, original_price:1199, unit:'瓶/500ml', qr_prefix:'MT1935', is_hot:true, is_new:false, rating:4.8, reviews:8900, sold_count:3200, stock:120, tags:['1935系列','次高端','宴请主力'], tasting_notes:'以1935年为名，酱香馥郁，回味悠长，是目前次高端市场的主力产品', ai_pairing:['高端宴请','商务会客','节日送礼'] },

  // ── 更多酱香 ──
  { id:'xijiu-xijian-500', name:'习酒·习坛 酱香型 500ml', category:'baijiu-sauce', brand:'习酒', year:2023, degree:53, price:478, original_price:598, unit:'瓶/500ml', qr_prefix:'XJXJ', is_hot:true, is_new:false, rating:4.7, reviews:3400, sold_count:2800, stock:200, tags:['贵州习酒','酱香纯正','商务宴请'], tasting_notes:'习酒旗下高端产品，酱香突出，口感醇厚，回味绵长', ai_pairing:['川贵菜系','商务宴席','高端聚会'] },
  { id:'guotai-15', name:'国台·国标15年 酱香型', category:'baijiu-sauce', brand:'国台', year:2024, degree:53, price:598, original_price:728, unit:'瓶/500ml', qr_prefix:'GT15', is_hot:false, is_new:false, rating:4.6, reviews:1200, sold_count:680, stock:90, tags:['15年基酒','酱香典范','品鉴佳酿'], tasting_notes:'以15年以上老酒为基，酱香馥郁，陈香优雅，层次丰富', ai_pairing:['清蒸鱼','贵州腊肉','豆腐乳'] },
  { id:'diaoyutai-8', name:'钓鱼台 8年陈酿 酱香型', category:'baijiu-sauce', brand:'钓鱼台', year:2024, degree:53, price:398, original_price:488, unit:'瓶/500ml', qr_prefix:'DYT8', is_hot:false, is_new:false, rating:4.5, reviews:890, sold_count:420, stock:80, tags:['国宴品质','8年陈酿','政务用酒'], tasting_notes:'国宴专用品质，酱香纯正，酒体醇厚，是品质宴请的优选', ai_pairing:['国宴菜式','商务接待','高端礼品'] },

  // ── 更多浓香 ──
  { id:'luzhou-tequ', name:'泸州老窖 特曲 浓香型', category:'baijiu-strong', brand:'泸州老窖', year:2024, degree:52, price:128, original_price:168, unit:'瓶/500ml', qr_prefix:'LZTQ', is_hot:true, is_new:false, rating:4.5, reviews:12000, sold_count:35000, stock:2000, tags:['百年老窖','浓香经典','大众口粮'], tasting_notes:'泸州老窖经典产品，浓香醇厚，绵甜干净，是大众浓香口粮酒首选', ai_pairing:['川菜','火锅','家庭聚餐'] },
  { id:'yanghe-mengzhilan', name:'洋河·梦之蓝M6+ 绵柔型', category:'baijiu-strong', brand:'洋河', year:2024, degree:45, price:458, original_price:558, unit:'瓶/500ml', qr_prefix:'YHMZL', is_hot:true, is_new:false, rating:4.7, reviews:18000, sold_count:25000, stock:600, tags:['梦之蓝','绵柔浓香','次高端主力'], tasting_notes:'洋河绵柔代表作，入口绵柔甜润，香气幽雅，是次高端宴请的热门之选', ai_pairing:['苏帮菜','淮扬菜','商务宴请'] },
  { id:'jiannanchun-water', name:'剑南春 水晶剑 浓香型', category:'baijiu-strong', brand:'剑南春', year:2024, degree:52, price:238, original_price:298, unit:'瓶/500ml', qr_prefix:'JNC', is_hot:false, is_new:false, rating:4.5, reviews:8900, sold_count:15000, stock:800, tags:['四川名酒','浓香纯正','宴请实惠'], tasting_notes:'四川传统浓香名酒，香气浓郁，口感绵甜，余味悠长，宴请性价比极高', ai_pairing:['川味小炒','麻辣火锅','家庭宴席'] },
  { id:'wuliangye-1618', name:'五粮液 1618 浓香型', category:'baijiu-strong', brand:'五粮液', year:2024, degree:52, price:658, original_price:798, unit:'瓶/500ml', qr_prefix:'WLY1618', is_hot:true, is_new:false, rating:4.8, reviews:9800, sold_count:5600, stock:300, tags:['五粮精酿','次高端旗舰','宴请主力'], tasting_notes:'五粮液次高端旗舰产品，浓香馥郁，五谷芳香层叠，口感圆润饱满', ai_pairing:['高端宴席','商务接待','节日送礼'] },

  // ── 更多威士忌 ──
  { id:'glenlivet-12', name:'格兰威特 12年 单一麦芽', category:'whisky', brand:'格兰威特', year:12, degree:40, price:328, original_price:420, unit:'瓶/700ml', qr_prefix:'GL12', is_hot:false, is_new:false, rating:4.4, reviews:5600, sold_count:4200, stock:180, tags:['斯佩塞','入门首选','花果香'], tasting_notes:'柑橘花香，香草奶油，清爽易饮，是单一麦芽威士忌入门的经典之选', ai_pairing:['甜点','坚果','水果拼盘'] },
  { id:'bowmore-12', name:'波摩 12年 艾雷岛单一麦芽', category:'whisky', brand:'波摩', year:12, degree:40, price:428, original_price:560, unit:'瓶/700ml', qr_prefix:'BW12', is_hot:false, is_new:false, rating:4.5, reviews:2300, sold_count:1800, stock:65, tags:['艾雷岛','轻泥煤','花香熏烟'], tasting_notes:'温和泥煤烟熏，紫罗兰花香，黑巧克力，适合初尝艾雷岛泥煤风格', ai_pairing:['烟熏三文鱼','黑巧克力','生蚝'] },
  { id:'johnnie-walker-blue', name:'尊尼获加 蓝牌 调和威士忌', category:'whisky', brand:'帝亚吉欧', year:0, degree:40, price:1280, original_price:1680, unit:'瓶/700ml', qr_prefix:'JWBLUE', is_hot:true, is_new:false, rating:4.8, reviews:4500, sold_count:2100, stock:55, tags:['蓝牌顶级','调和之王','礼品首选'], tasting_notes:'万桶精选，蜂蜜香草，丝绸般顺滑，余韵悠长，是商务礼赠的顶级之选', ai_pairing:['黑巧克力','奶酪拼盘','烟熏肉'] },

  // ── 更多红酒 ──
  { id:'penfolds-bin407', name:'奔富 BIN407 赤霞珠干红', category:'red-wine', brand:'奔富', year:2021, degree:14, price:388, original_price:498, unit:'瓶/750ml', qr_prefix:'PF407', is_hot:true, is_new:false, rating:4.7, reviews:8900, sold_count:6800, stock:280, tags:['澳洲名庄','赤霞珠','大众高端'], tasting_notes:'黑醋栗、薄荷、橡木香，单宁成熟，结构均衡，是奔富系列中的人气之选', ai_pairing:['牛排','羊排','烤肉'] },
  { id:'changyu-cabernet', name:'张裕 解百纳·蛇龙珠 干红', category:'red-wine', brand:'张裕', year:2022, degree:13, price:168, original_price:218, unit:'瓶/750ml', qr_prefix:'ZYCBN', is_hot:false, is_new:false, rating:4.3, reviews:15000, sold_count:28000, stock:1200, tags:['国产名庄','百年传承','性价比高'], tasting_notes:'果香浓郁，单宁柔顺，口感圆润，是国产高性价比干红的代表', ai_pairing:['中式红烧菜','烤鸭','牛肉'] },
  { id:'great-wall-gold', name:'长城 金标赤霞珠 干红', category:'red-wine', brand:'长城', year:2022, degree:13, price:128, original_price:168, unit:'瓶/750ml', qr_prefix:'GCGOLD', is_hot:false, is_new:false, rating:4.2, reviews:12000, sold_count:35000, stock:2000, tags:['国产经典','宴席用酒','实惠大众'], tasting_notes:'色泽深红，果香清新，入口柔和，是宴席用酒的高性价比选择', ai_pairing:['家常红烧菜','烤肉','日常聚餐'] },
  { id:'castel-classic', name:'卡斯特 经典波尔多干红', category:'red-wine', brand:'卡斯特', year:2021, degree:13, price:198, original_price:268, unit:'瓶/750ml', qr_prefix:'CASC', is_hot:false, is_new:false, rating:4.4, reviews:6700, sold_count:9800, stock:500, tags:['法国进口','波尔多','入门法国酒'], tasting_notes:'黑莓、李子、轻微橡木，单宁柔顺，是入门法国波尔多的好选择', ai_pairing:['羊排','鸭胸肉','硬质奶酪'] },

  // ── 更多干邑 ──
  { id:'martell-vsop', name:'马爹利 VSOP 蓝带干邑', category:'cognac', brand:'马爹利', year:0, degree:40, price:468, original_price:598, unit:'瓶/700ml', qr_prefix:'MVSOP', is_hot:true, is_new:false, rating:4.6, reviews:7800, sold_count:5600, stock:220, tags:['VSOP经典','马爹利蓝带','法国进口'], tasting_notes:'杏仁、橡木、香草，口感圆润平衡，是商务宴请的高性价比干邑选择', ai_pairing:['黑巧克力','坚果拼盘','奶酪'] },
  { id:'camus-vsop', name:'卡慕 VSOP 特酿干邑', category:'cognac', brand:'卡慕', year:0, degree:40, price:398, original_price:498, unit:'瓶/700ml', qr_prefix:'CAMVSOP', is_hot:false, is_new:false, rating:4.5, reviews:2100, sold_count:1400, stock:80, tags:['家族酒庄','精品干邑','花香清雅'], tasting_notes:'花香清雅，李子干果，橡木香草，余韵悠长，是精品干邑的优质选择', ai_pairing:['蜂蜜蛋糕','干果','黑巧克力'] },

  // ── 果酒 (0→有) ──
  { id:'mei-jian-plum', name:'梅见 青梅酒 原味', category:'fruit-wine', brand:'梅见', year:2024, degree:12, price:58, original_price:78, unit:'瓶/500ml', qr_prefix:'MJ500', is_hot:true, is_new:false, rating:4.8, reviews:58000, sold_count:180000, stock:5000, tags:['青梅酿造','微酸甜口','女生最爱'], tasting_notes:'新鲜青梅酿造，酸甜怡人，梅香清雅，低度易饮，是果酒市场的现象级产品', ai_pairing:['日式料理','轻食','甜品'] },
  { id:'reci-lychee', name:'醴七 荔枝酒 岭南风味', category:'fruit-wine', brand:'醴七', year:2024, degree:10, price:88, original_price:118, unit:'瓶/500ml', qr_prefix:'LZ500', is_hot:false, is_new:true, rating:4.6, reviews:3200, sold_count:8900, stock:600, tags:['荔枝酿造','岭南特色','清甜果香'], tasting_notes:'广东荔枝鲜果酿造，荔枝清甜，果香馥郁，低度清爽，夏季饮用极佳', ai_pairing:['粤式点心','清蒸海鲜','水果甜点'] },
  { id:'bodhi-cherry', name:'菩提 车厘子红酒 果味酒', category:'fruit-wine', brand:'菩提', year:2024, degree:8, price:68, original_price:88, unit:'瓶/750ml', qr_prefix:'BT750', is_hot:false, is_new:false, rating:4.4, reviews:4500, sold_count:12000, stock:800, tags:['车厘子果酒','微甜红酒风','派对必备'], tasting_notes:'车厘子果香浓郁，微甜顺口，低度清爽，是聚会派对的热门选择', ai_pairing:['甜品','水果拼盘','轻食派对'] },

  // ── 保健酒 (0→有) ──
  { id:'zhongliege-health', name:'中猎格 参茸鹿鞭健康酒 500ml', category:'health-wine', brand:'中猎格', year:2024, degree:38, price:268, original_price:368, unit:'瓶/500ml', qr_prefix:'ZLG500', is_hot:false, is_new:false, rating:4.5, reviews:2800, sold_count:3200, stock:180, tags:['参茸配方','男性保健','滋补养生'], tasting_notes:'精选人参、鹿茸、枸杞等名贵药材，酒体醇厚，滋补效果显著', ai_pairing:['小饮适量','温热服用','睡前一杯'] },
  { id:'quanjude-yangsheng', name:'劲酒 35° 保健酒', category:'health-wine', brand:'劲酒', year:2024, degree:35, price:48, original_price:62, unit:'瓶/125ml×6', qr_prefix:'JJ125', is_hot:true, is_new:false, rating:4.5, reviews:45000, sold_count:280000, stock:10000, tags:['经典劲酒','草本配方','大众保健'], tasting_notes:'草本药材与白酒完美融合，香气宜人，入口醇和，是国民级保健酒代表', ai_pairing:['温热饮用','适量小酌','餐前开胃'] },
  { id:'wu-jia-pi', name:'五加皮酒 传统养生酒', category:'health-wine', brand:'致中和', year:2024, degree:39, price:88, original_price:118, unit:'瓶/500ml', qr_prefix:'WJP500', is_hot:false, is_new:false, rating:4.3, reviews:3400, sold_count:5600, stock:320, tags:['五加皮','草本养生','浙江传统'], tasting_notes:'传统五加皮配方，药香浓郁，入口甜润，有祛风湿、强筋骨之效', ai_pairing:['温热饮用','适量小酌','养生调理'] },

  // ── 黄酒 (0→有) ──
  { id:'guyue-longshen', name:'古越龙山 金五年 绍兴黄酒', category:'huangjiu', brand:'古越龙山', year:5, degree:15, price:68, original_price:88, unit:'瓶/500ml', qr_prefix:'GYLS5', is_hot:true, is_new:false, rating:4.6, reviews:12000, sold_count:35000, stock:3000, tags:['绍兴经典','五年陈酿','佐餐必备'], tasting_notes:'绍兴传统黄酒，醇香浓郁，入口柔顺，是江南风味佐餐的绝佳伴侣', ai_pairing:['大闸蟹','清蒸鱼','上海本帮菜'] },
  { id:'shaoxing-nverhong', name:'会稽山 女儿红 十年陈酿', category:'huangjiu', brand:'会稽山', year:10, degree:16, price:128, original_price:168, unit:'瓶/750ml', qr_prefix:'NVH10', is_hot:false, is_new:false, rating:4.7, reviews:5600, sold_count:9800, stock:600, tags:['女儿红','十年陈酿','婚宴佳品'], tasting_notes:'色泽琥珀，陈香幽雅，回味绵长，是婚宴与喜庆场合的传统佳酿', ai_pairing:['婚宴','大闸蟹','腌制食品'] },
  { id:'tapai-mijiu', name:'塔牌 传统型绍兴米酒', category:'huangjiu', brand:'塔牌', year:3, degree:15, price:38, original_price:48, unit:'瓶/500ml', qr_prefix:'TP500', is_hot:false, is_new:false, rating:4.4, reviews:8900, sold_count:22000, stock:2000, tags:['绍兴米酒','传统工艺','烹饪调酒两用'], tasting_notes:'米香纯正，口感醇和，既可品饮，也是江南菜肴烹饪的上等料酒', ai_pairing:['江南菜系','清蒸海鲜','糟卤食品'] },

  // ── 鸡尾酒 (0→有) ──
  { id:'rio-cocktail-lychee', name:'RIO 锐澳 荔枝味鸡尾酒', category:'cocktail', brand:'RIO', year:2024, degree:3.8, price:12, original_price:16, unit:'罐/330ml', qr_prefix:'RIO330L', is_hot:true, is_new:false, rating:4.5, reviews:85000, sold_count:500000, stock:20000, tags:['低度甜口','女生最爱','冰镇必备'], tasting_notes:'荔枝果香清甜，微醺低度，冰镇后饮用口感最佳，是派对聚会的标配', ai_pairing:['烧烤聚会','轻食派对','KTV欢乐'] },
  { id:'bacardi-white', name:'百加得 白朗姆酒 基酒', category:'cocktail', brand:'百加得', year:2024, degree:40, price:128, original_price:168, unit:'瓶/750ml', qr_prefix:'BAC750', is_hot:false, is_new:false, rating:4.5, reviews:6700, sold_count:8900, stock:400, tags:['调酒基酒','朗姆经典','古巴利格拉'],  tasting_notes:'清爽干净，蔗糖香草，是调制莫吉托、椰林飘香等经典鸡尾酒的最佳基酒', ai_pairing:['莫吉托调酒','椰汁调饮','热带水果'] },
  { id:'wuliangye-cocktail-ready', name:'五粮液 鸡尾酒预调 系列礼盒', category:'cocktail', brand:'五粮液', year:2024, degree:5, price:168, original_price:218, unit:'盒/6罐×330ml', qr_prefix:'WLYCT', is_hot:false, is_new:true, rating:4.4, reviews:1200, sold_count:2800, stock:500, tags:['五粮液出品','预调礼盒','6款风味'], tasting_notes:'五粮液基酒调制，覆盆子、青柠、百香果等6款风味，低度清爽，聚会必备', ai_pairing:['家庭派对','朋友聚会','户外烧烤'] },

  // ── 更多下酒菜 ──
  { id:'food-peanut-premium', name:'手工老醋花生米 下酒必备', category:'food', brand:'百邑食品', year:2024, degree:0, price:28, original_price:38, unit:'袋/200g', qr_prefix:'FPN200', is_hot:true, is_new:false, rating:4.6, reviews:28000, sold_count:120000, stock:5000, tags:['老醋调味','酥脆下酒','即食零食'], tasting_notes:'手工炒制，老陈醋腌渍，酥脆咸香，是配白酒的国民下酒小食', ai_pairing:['茅台','五粮液','所有白酒'] },
  { id:'food-beef-jerky', name:'内蒙古风干牛肉干 原味', category:'food', brand:'草原恋', year:2024, degree:0, price:88, original_price:118, unit:'袋/200g', qr_prefix:'BJ200', is_hot:false, is_new:false, rating:4.7, reviews:18000, sold_count:45000, stock:2000, tags:['内蒙古原产','自然风干','高蛋白零食'], tasting_notes:'内蒙古草原黄牛，自然风干，嚼劲十足，肉香浓郁，是配酒的经典硬菜小食', ai_pairing:['威士忌','红酒','白酒'] },
  { id:'food-smoked-salmon', name:'挪威烟熏三文鱼 切片装', category:'food', brand:'皇家海鲜', year:2024, degree:0, price:188, original_price:248, unit:'盒/200g切片', qr_prefix:'SS200', is_hot:false, is_new:false, rating:4.8, reviews:5600, sold_count:8900, stock:300, tags:['挪威进口','冷烟熏制','配酒之王'], tasting_notes:'挪威峡湾三文鱼，冷熏工艺，橙红油润，与威士忌、白葡萄酒绝配', ai_pairing:['拉弗格威士忌','白葡萄酒','起泡酒'] },

  // ── 更多礼品 ──
  { id:'gift-wine-trio', name:'百邑精选三瓶装礼盒 中西合璧', category:'gift', brand:'百邑酒世界', year:2024, degree:0, price:1280, original_price:1680, unit:'盒/3款各375ml', qr_prefix:'GWTRIO', is_hot:false, is_new:true, rating:4.9, reviews:680, sold_count:420, stock:80, tags:['中西合璧','三款精选','顶级礼品'], tasting_notes:'茅台王子+麦卡伦12+拉菲珍宝，一盒汇聚中西顶级风味，是最高端的商务礼品', ai_pairing:['顶级商务礼赠','节日馈赠','收藏品鉴'] },
  { id:'gift-mooncake-wine', name:'月圆酒香·中秋礼盒 酒+月饼', category:'gift', brand:'百邑酒世界', year:2024, degree:0, price:488, original_price:628, unit:'盒/酒+月饼套装', qr_prefix:'MC2024', is_hot:true, is_new:false, rating:4.8, reviews:2300, sold_count:5600, stock:200, tags:['中秋限定','酒饼组合','节日首选'], tasting_notes:'茅台王子酒配精品广式月饼，中秋节令限定礼盒，送礼面面俱到', ai_pairing:['中秋赏月','走亲访友','节日送礼'] },
];

export const MOCK_STORES = [
  {
    id: 's1',
    name: '百邑酒世界·旗舰店',
    address: '广东省广州市天河区天河路385号太古汇B1层',
    lat: 23.1347, lng: 113.3239,
    phone: '020-8888-8888',
    hours: '10:00 - 22:00',
    rating: 4.9, distance: '0.3km', type: '旗舰店',
    tags: ['茅台专柜', '威士忌体验区', '雪茄室'],
    is_open: true,
    video_url: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 's2',
    name: '百邑酒世界·珠江新城店',
    address: '广州市天河区珠江新城华就路28号',
    lat: 23.1205, lng: 113.3246,
    phone: '020-7777-6666',
    hours: '10:30 - 21:30',
    rating: 4.7, distance: '1.2km', type: '精品店',
    tags: ['洋酒专区', '礼品定制'],
    is_open: true,
    video_url: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 's3',
    name: '百邑酒世界·番禺万达店',
    address: '广州市番禺区迎宾路万达广场3F-B区',
    lat: 22.9578, lng: 113.3542,
    phone: '020-6666-5555',
    hours: '10:00 - 22:00',
    rating: 4.6, distance: '15km', type: '标准店',
    tags: ['白酒专营'],
    is_open: false,
    video_url: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 's4',
    name: '百邑酒世界·越秀正佳店',
    address: '广州市越秀区中山五路正佳广场L4',
    lat: 23.1287, lng: 113.2895,
    phone: '020-5555-4444',
    hours: '10:00 - 21:00',
    rating: 4.8, distance: '3.5km', type: '精品店',
    tags: ['红酒体验', '进口啤酒', '茗茶'],
    is_open: true,
    video_url: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
];

export const MOCK_CARDS = {
  'BY-2024-001': { balance: 5000, total: 5000, status: 'active',  expire: '2026-12-31' },
  'BY-2024-002': { balance: 2800, total: 3000, status: 'active',  expire: '2026-06-30' },
  'BY-2024-003': { balance: 0,    total: 1000, status: 'used',    expire: '2025-12-31' },
  'BY-DEMO-888': { balance: 888,  total: 888,  status: 'active',  expire: '2027-01-01' },
  'BAIY-2024-8A3F9E': { balance: 650, total: 1000, status: 'active', expire: '2026-01-15',
    transactions: [
      { date: '2024-03-10', store: '百邑酒行·天河旗舰店', amount: -350, item: '贵州茅台×1' }
    ]
  },
};

export const MOCK_INVENTORY_STATS = {
  total_skus: 128,
  low_stock_count: 7,
  out_of_stock_count: 2,
  today_sales: 38,
  today_revenue: 62480,
  recent_scans: [
    { id: 1, sku: 'MT-2015-001', name: '茅台2015年飞天', action: 'OUT', qty: 2, time: '14:32' },
    { id: 2, sku: 'HN-XO-700',  name: '轩尼诗XO 700ml', action: 'IN',  qty: 12, time: '13:18' },
    { id: 3, sku: 'MC-18-SH',   name: '麦卡伦18年雪莉', action: 'OUT', qty: 1, time: '12:45' },
    { id: 4, sku: 'LF-ZB-2020', name: '拉菲珍宝2020',   action: 'OUT', qty: 3, time: '11:20' },
    { id: 5, sku: 'MT-2018-001', name: '茅台2018年精飞', action: 'IN',  qty: 6, time: '10:55' },
    { id: 6, sku: 'GF-15-SL',   name: '格兰菲迪15年',   action: 'IN',  qty: 4, time: '10:10' },
    { id: 7, sku: 'DS-DG-39',   name: '獭祭大吟酿39',   action: 'OUT', qty: 8, time: '09:40' },
  ],
};
