// ─────────────────────────────────────────
//  百邑酒世界 · 全量 Mock 数据（扩充版）
// ─────────────────────────────────────────

export const MOCK_CATEGORIES = [
  { id: 'maotai',         name: '年份茅台',   icon: '🏺', slug: 'maotai',         color: '#C8A96E', hot: true  },
  { id: 'baijiu-sauce',   name: '酱香白酒',   icon: '🍶', slug: 'baijiu-sauce',   color: '#D4784A', hot: false },
  { id: 'baijiu-strong',  name: '浓香白酒',   icon: '🫙', slug: 'baijiu-strong',  color: '#8B6914', hot: false },
  { id: 'cognac',         name: '干邑白兰地', icon: '🍾', slug: 'cognac',         color: '#9C2935', hot: false },
  { id: 'whisky',         name: '威士忌',     icon: '🥃', slug: 'whisky',         color: '#8B4513', hot: true  },
  { id: 'red-wine',       name: '红葡萄酒',   icon: '🍷', slug: 'red-wine',       color: '#8B0000', hot: false },
  { id: 'vodka',          name: '伏特加',     icon: '🥂', slug: 'vodka',          color: '#4A90D9', hot: false },
  { id: 'sake',           name: '清酒',       icon: '🫙', slug: 'sake',           color: '#C8AD7F', hot: false },
  { id: 'beer-import',    name: '进口啤酒',   icon: '🍺', slug: 'beer-import',    color: '#D4820A', hot: false },
  { id: 'tea',            name: '茗茶茶具',   icon: '🫖', slug: 'tea',            color: '#27AE60', hot: false },
  { id: 'cigar',          name: '精品雪茄',   icon: '🚬', slug: 'cigar',          color: '#795548', hot: false },
  { id: 'gift',           name: '手信礼品',   icon: '🎁', slug: 'gift',           color: '#E91E8C', hot: false },
  { id: 'food',           name: '下酒好菜',   icon: '🥩', slug: 'food',           color: '#FF5722', hot: false },
  { id: 'flash-sale',     name: '特价促销',   icon: '🔥', slug: 'flash-sale',     color: '#F44336', hot: true  },
];

export const MOCK_ADS = [
  {
    id: 1,
    title: '年份个性化茅台',
    subtitle: '传世珍品，酱香典范，匠心酿造五十年',
    eyebrow: '镇店之宝',
    cta: '立即抢购',
    link: '/category/maotai',
    bg: 'linear-gradient(135deg, #1a0e00 0%, #3d2200 50%, #1a0e00 100%)',
    accentColor: 'rgba(200,169,110,0.45)',
  },
  {
    id: 2,
    title: '轩尼诗 XO 限时直降',
    subtitle: '法兰西顶级干邑，馥郁花香，丝滑绵长',
    eyebrow: '限时特惠',
    cta: '查看详情',
    link: '/category/cognac',
    bg: 'linear-gradient(135deg, #1a0505 0%, #4a0505 50%, #1a0505 100%)',
    accentColor: 'rgba(180,30,30,0.5)',
  },
  {
    id: 3,
    title: '百邑购物卡·区块链护航',
    subtitle: '零风险礼赠，链上存证，兑完即毁不留痕',
    eyebrow: '安全无忧',
    cta: '购卡查余额',
    link: '/card',
    bg: 'linear-gradient(135deg, #050520 0%, #0d1545 50%, #050520 100%)',
    accentColor: 'rgba(30,100,229,0.5)',
  },
  {
    id: 4,
    title: 'AI 直播间·品酒大师',
    subtitle: '每晚 20:00 准时开播，独家折扣实时抢购',
    eyebrow: '正在直播',
    cta: '进入直播间',
    link: '/live',
    bg: 'linear-gradient(135deg, #1a0530 0%, #35085a 50%, #1a0530 100%)',
    accentColor: 'rgba(142,36,170,0.55)',
  },
  {
    id: 5,
    title: '麦卡伦 18年 雪莉桶',
    subtitle: '苏格兰斯佩塞威士忌翘楚，干果可可绵密层次',
    eyebrow: '年度爆款',
    cta: '限时优惠',
    link: '/category/whisky',
    bg: 'linear-gradient(135deg, #1a0800 0%, #3d1500 50%, #1a0800 100%)',
    accentColor: 'rgba(180,100,20,0.5)',
  },
];

export const MOCK_PRODUCTS = [
  // ── 茅台 ───────────────────────────────────────────────────────
  {
    id: 'mt-2015-53',
    name: '贵州茅台 2015年 飞天',
    category: 'maotai', brand: '茅台',
    year: 2015, degree: 53,
    price: 2680, original_price: 3200,
    unit: '瓶/500ml', qr_prefix: 'MT201553',
    is_hot: true, is_new: false,
    rating: 5, reviews: 3821, sold_count: 520, stock: 38,
    tags: ['飞天陈年', '酱香收藏级', '有价无市'],
    tasting_notes: '酱香突出，幽雅细腻，酒体醇厚，回味悠长，空杯留香超60秒',
    ai_pairing: ['清蒸武昌鱼', '贵州腊肉', '豆腐乳'],
  },
  {
    id: 'mt-2021-53',
    name: '贵州茅台 2021年 飞天',
    category: 'maotai', brand: '茅台',
    year: 2021, degree: 53,
    price: 1499, original_price: 1799,
    unit: '瓶/500ml', qr_prefix: 'MT202153',
    is_hot: true, is_new: false,
    rating: 4.9, reviews: 2890, sold_count: 980, stock: 58,
    tags: ['经典飞天', '酱香', '宴请首选'],
    tasting_notes: '酱香正宗，入口柔顺，余韵绵长，是入门飞天的最佳选择',
    ai_pairing: ['粤式白切鸡', '清淡小菜', '生蚝'],
  },
  {
    id: 'mt-2018-53-jf',
    name: '贵州茅台 2018年 精飞',
    category: 'maotai', brand: '茅台',
    year: 2018, degree: 53,
    price: 1980, original_price: 2388,
    unit: '瓶/500ml', qr_prefix: 'MT201853',
    is_hot: false, is_new: false,
    rating: 5, reviews: 2076, sold_count: 420, stock: 45,
    tags: ['精品飞天', '酱香馥郁', '投资佳品'],
    tasting_notes: '酱香馥郁，陈香优雅，醇厚圆润，空杯留香持久悠扬',
    ai_pairing: ['鱼子酱', '黑松露菜肴', '清淡粤菜'],
  },
  {
    id: 'mt-2024-43',
    name: '贵州茅台 2024年 低度版',
    category: 'maotai', brand: '茅台',
    year: 2024, degree: 43,
    price: 1299, original_price: 1399,
    unit: '瓶/500ml', qr_prefix: 'MT202443',
    is_hot: false, is_new: true,
    rating: 4.7, reviews: 512, sold_count: 280, stock: 200,
    tags: ['低度入门', '花香宜人', '新品上市'],
    tasting_notes: '度数柔和，花香明显，易于入口，适合初次品味酱香的饮酒者',
    ai_pairing: ['海鲜沙拉', '水果拼盘', '轻食甜点'],
  },

  // ── 酱香白酒 ──────────────────────────────────────────────────
  {
    id: 'langjiu-honghuarlang-500',
    name: '郎酒·红花郎 10年',
    category: 'baijiu-sauce', brand: '郎酒',
    year: 2014, degree: 53,
    price: 328, original_price: 428,
    unit: '瓶/500ml', qr_prefix: 'LJ201453',
    is_hot: false, is_new: true,
    rating: 4.6, reviews: 2140, sold_count: 680, stock: 120,
    tags: ['酱香典雅', '性价比高', '宴请佳选'],
    tasting_notes: '红樱桃花香，入口绵柔，酱香幽雅，回味舒适持久',
    ai_pairing: ['红烧肉', '卤猪蹄', '酸笋炒肉'],
  },
  {
    id: 'jinmendao-baijiu-2018',
    name: '金门高粱酒 1992限定',
    category: 'baijiu-sauce', brand: '金门',
    year: 1992, degree: 58,
    price: 1280, original_price: 1680,
    unit: '瓶/600ml', qr_prefix: 'JM199258',
    is_hot: false, is_new: false,
    rating: 4.8, reviews: 318, sold_count: 95, stock: 15,
    tags: ['1992绝版', '粮香清雅', '台湾精品'],
    tasting_notes: '粮香清雅，入口辛辣回甘，余韵持久，是品鉴台湾高粱的上选',
    ai_pairing: ['凤梨酥', '烤肉串', '台式卤猪脚'],
  },
  {
    id: 'wuliangye-pujin-2024',
    name: '五粮液 普金 2024年',
    category: 'baijiu-strong', brand: '五粮液',
    year: 2024, degree: 52,
    price: 889, original_price: 1099,
    unit: '瓶/500ml', qr_prefix: 'WLY202452',
    is_hot: false, is_new: true,
    rating: 4.7, reviews: 782, sold_count: 290, stock: 150,
    tags: ['浓香醇厚', '五粮精酿', '新品上市'],
    tasting_notes: '浓香醇厚，粮香丰富，陈香悠长，口感绵甜，回味干净',
    ai_pairing: ['川式麻辣火锅', '宫保鸡丁', '粉蒸肉'],
  },

  // ── 干邑 ──────────────────────────────────────────────────────
  {
    id: 'hennessy-xo-700',
    name: '轩尼诗 XO 700ml',
    category: 'cognac', brand: '轩尼诗',
    year: 0, degree: 40,
    price: 1560, original_price: 2100,
    unit: '瓶/700ml', qr_prefix: 'HXO700',
    is_hot: true, is_new: false,
    rating: 4.9, reviews: 2104, sold_count: 380, stock: 55,
    tags: ['XO经典', '礼品首选', '法国进口'],
    tasting_notes: '馥郁花香，丰满圆润，橡木与香草气息缓缓展开，余韵如丝绸般顺滑',
    ai_pairing: ['黑巧克力', '奶酪拼盘', '鹅肝酱'],
  },
  {
    id: 'ct-blue-star-2023',
    name: '轩尼诗 VSOP 特酿',
    category: 'cognac', brand: '轩尼诗',
    year: 0, degree: 40,
    price: 568, original_price: 720,
    unit: '瓶/700ml', qr_prefix: 'HVSOP',
    is_hot: false, is_new: false,
    rating: 4.5, reviews: 1503, sold_count: 720, stock: 210,
    tags: ['VSOP入门', '性价比高', '调酒佳品'],
    tasting_notes: '香草橡木，烤糖蜜香，细腻平衡，是入门干邑的经典之选',
    ai_pairing: ['冰激凌', '焦糖布丁', '干果拼盘'],
  },
  {
    id: 'remy-martin-xo',
    name: '人头马 XO 卓越干邑',
    category: 'cognac', brand: '人头马',
    year: 0, degree: 40,
    price: 1380, original_price: 1680,
    unit: '瓶/700ml', qr_prefix: 'RMXO700',
    is_hot: false, is_new: false,
    rating: 4.8, reviews: 1201, sold_count: 260, stock: 40,
    tags: ['百年老厂', '大香槟区', '卓越品质'],
    tasting_notes: '圆润顺滑，干花、蜂蜜、李子与橡木交织，层次丰富，余韵悠长',
    ai_pairing: ['蓝纹奶酪', '核桃仁', '黑松露'],
  },

  // ── 威士忌 ────────────────────────────────────────────────────
  {
    id: 'macallan-18-sherry',
    name: '麦卡伦 18年 雪莉桶',
    category: 'whisky', brand: '麦卡伦',
    year: 18, degree: 43,
    price: 3280, original_price: 4200,
    unit: '瓶/700ml', qr_prefix: 'MC18SH',
    is_hot: true, is_new: false,
    rating: 5, reviews: 1892, sold_count: 210, stock: 22,
    tags: ['18年陈酿', '雪莉桶', '苏格兰之王'],
    tasting_notes: '饱满干果、黑巧克力、橡木香辛，层次丰富，余韵悠长绵密',
    ai_pairing: ['蓝纹奶酪', '烟熏三文鱼', '黑巧克力'],
  },
  {
    id: 'glenfiddich-15-solera',
    name: '格兰菲迪 15年 索雷拉',
    category: 'whisky', brand: '格兰菲迪',
    year: 15, degree: 40,
    price: 680, original_price: 880,
    unit: '瓶/700ml', qr_prefix: 'GF15SL',
    is_hot: false, is_new: true,
    rating: 4.5, reviews: 654, sold_count: 180, stock: 66,
    tags: ['索雷拉桶', '奶油风味', '入门首选'],
    tasting_notes: '奶油香草，成熟果实，雪莉甜蜜，余韵温暖，适合初尝斯佩塞风格',
    ai_pairing: ['提拉米苏', '蜂蜜蛋糕', '干果巧克力'],
  },
  {
    id: 'chivas-regal-18',
    name: '芝华士 18年 金玺',
    category: 'whisky', brand: '芝华士',
    year: 18, degree: 40,
    price: 480, original_price: 620,
    unit: '瓶/700ml', qr_prefix: 'CR18',
    is_hot: false, is_new: false,
    rating: 4.4, reviews: 2231, sold_count: 880, stock: 320,
    tags: ['调和威士忌', '大众熟知', '宴请定番'],
    tasting_notes: '蜂蜜黑巧克力，烤坚果，奶油柔滑，尾段温暖，适合宴请场合',
    ai_pairing: ['烟熏肉', '苹果派', '焦糖布丁'],
  },
  {
    id: 'laphroaig-10',
    name: '拉弗格 10年 艾雷岛单一麦芽',
    category: 'whisky', brand: '拉弗格',
    year: 10, degree: 43,
    price: 520, original_price: 680,
    unit: '瓶/700ml', qr_prefix: 'LF10IS',
    is_hot: false, is_new: false,
    rating: 4.6, reviews: 876, sold_count: 340, stock: 88,
    tags: ['艾雷岛泥煤', '正宗烟熏', '个性化'],
    tasting_notes: '强烈碘味与泥煤烟熏，夹杂海盐柠檬气息，极具个性，令人难忘',
    ai_pairing: ['生蚝', '烟熏三文鱼', '黑胡椒牛排'],
  },

  // ── 红葡萄酒 ──────────────────────────────────────────────────
  {
    id: 'lafite-zhuanbao-2020',
    name: '拉菲珍宝 2020',
    category: 'red-wine', brand: '拉菲',
    year: 2020, degree: 13,
    price: 680, original_price: 888,
    unit: '瓶/750ml', qr_prefix: 'LFZB2020',
    is_hot: true, is_new: false,
    rating: 4.7, reviews: 956, sold_count: 340, stock: 80,
    tags: ['拉菲系列', '波尔多产区', '日常餐酒'],
    tasting_notes: '黑醋栗、雪松香气，单宁丝滑，果香充沛，是波尔多入门佳作',
    ai_pairing: ['战斧牛排', '羊排', '蘑菇意大利面'],
  },
  {
    id: 'mouton-2019',
    name: '木桐庄园 2019年',
    category: 'red-wine', brand: '木桐',
    year: 2019, degree: 14,
    price: 2180, original_price: 2800,
    unit: '瓶/750ml', qr_prefix: 'MT2019WE',
    is_hot: false, is_new: true,
    rating: 5, reviews: 412, sold_count: 88, stock: 20,
    tags: ['一级名庄', '97分', '可窖藏30年'],
    tasting_notes: '黑浆果、铅笔芯、玫瑰花瓣，单宁成熟精致，结构宏大壮丽',
    ai_pairing: ['红烩羊腿', '黑松露牛排', '成熟奶酪'],
  },
  {
    id: 'lafite-2019',
    name: '拉菲古堡正牌 2019年',
    category: 'red-wine', brand: '拉菲',
    year: 2019, degree: 13.5,
    price: 5800, original_price: 6500,
    unit: '瓶/750ml', qr_prefix: 'LF2019',
    is_hot: false, is_new: false,
    rating: 5, reviews: 289, sold_count: 55, stock: 6,
    tags: ['一级名庄', '波尔多正牌', '收藏级投资'],
    tasting_notes: '黑醋栗、雪松木香气层叠，结构宏大精密，可窖藏30年以上',
    ai_pairing: ['战斧牛排', '羊腿', '黑松露'],
  },

  // ── 伏特加 ────────────────────────────────────────────────────
  {
    id: 'smirnoff-gold',
    name: '皇冠伏特加 金装限定',
    category: 'vodka', brand: '皇冠',
    year: 2024, degree: 40,
    price: 289, original_price: 350,
    unit: '瓶/750ml', qr_prefix: 'SG2024',
    is_hot: false, is_new: true,
    rating: 4.4, reviews: 876, sold_count: 420, stock: 180,
    tags: ['金装限定', '纯粮蒸馏', '调酒首选'],
    tasting_notes: '晶莹纯净，入口极为柔和，无异味，适合纯饮或调制各类鸡尾酒',
    ai_pairing: ['鱼子酱', '腌三文鱼', '薯片小食'],
  },
  {
    id: 'absolut-elyx',
    name: '绝对伏特加 超级单一麦芽',
    category: 'vodka', brand: '绝对',
    year: 2023, degree: 42,
    price: 420, original_price: 560,
    unit: '瓶/700ml', qr_prefix: 'AE2023',
    is_hot: false, is_new: false,
    rating: 4.6, reviews: 542, sold_count: 195, stock: 65,
    tags: ['铜蒸馏', '手工精酿', '顶级品质'],
    tasting_notes: '柔滑奶油质地，淡淡谷物香气，回味干净悠长，纯饮最佳',
    ai_pairing: ['牡蛎', '柠檬慕斯', '北欧冷菜'],
  },

  // ── 清酒 ──────────────────────────────────────────────────────
  {
    id: 'dassai-junmai-daiginjo',
    name: '獭祭 纯米大吟酿 39',
    category: 'sake', brand: '旭酒造',
    year: 2024, degree: 16,
    price: 380, original_price: 480,
    unit: '瓶/720ml', qr_prefix: 'DS3924',
    is_hot: false, is_new: false,
    rating: 4.8, reviews: 1024, sold_count: 380, stock: 90,
    tags: ['纯米大吟酿', '精米39%', '日本清酒翘楚'],
    tasting_notes: '花香果香馥郁，清雅细腻，甘甜辛口平衡，是日本清酒的顶级代表',
    ai_pairing: ['刺身拼盘', '清蒸螃蟹', '豆腐料理'],
  },
  {
    id: 'kubota-manju',
    name: '久保田 万寿 无过滤',
    category: 'sake', brand: '朝日酒造',
    year: 2023, degree: 15,
    price: 520, original_price: 650,
    unit: '瓶/720ml', qr_prefix: 'KM2023',
    is_hot: false, is_new: false,
    rating: 4.7, reviews: 632, sold_count: 220, stock: 45,
    tags: ['无过滤', '原酒味道', '稀有限定'],
    tasting_notes: '米香浓郁，酒体饱满，原酒风味完整呈现，适合搭配浓郁料理',
    ai_pairing: ['烤和牛', '味噌汤', '炸猪排'],
  },

  // ── 进口啤酒 ──────────────────────────────────────────────────
  {
    id: 'chimay-blue',
    name: '智美 蓝帽 修道院啤酒',
    category: 'beer-import', brand: '智美',
    year: 2024, degree: 9,
    price: 58, original_price: 72,
    unit: '瓶/330ml', qr_prefix: 'CHBLUE',
    is_hot: false, is_new: false,
    rating: 4.8, reviews: 1563, sold_count: 2800, stock: 500,
    tags: ['修道院精酿', '比利时进口', '高度啤酒'],
    tasting_notes: '深邃果香，麦芽焦糖，丁香香料，尾段微苦而悠长，是精酿世界的巅峰',
    ai_pairing: ['炖牛尾', '野猪肉', '硬质奶酪'],
  },
  {
    id: 'weihenstephan-alkomas',
    name: '维恩斯蒂芬 白啤 500ml',
    category: 'beer-import', brand: '维恩斯蒂芬',
    year: 2024, degree: 5.4,
    price: 35, original_price: 45,
    unit: '瓶/500ml', qr_prefix: 'WS2024',
    is_hot: false, is_new: false,
    rating: 4.6, reviews: 2145, sold_count: 5200, stock: 800,
    tags: ['世界最古老酒厂', '德国小麦白啤', '浑浊酵母'],
    tasting_notes: '香蕉丁香泡泡糖香气，口感醇厚绵密，泡沫丰富持久',
    ai_pairing: ['德式猪肘', '椒盐脆薯', '白香肠'],
  },

  // ── 茗茶 ──────────────────────────────────────────────────────
  {
    id: 'dahongpao-gift',
    name: '武夷山大红袍 · 百邑臻品礼盒',
    category: 'tea', brand: '百邑茶叶',
    year: 2024, degree: 0,
    price: 1280, original_price: 1680,
    unit: '套/200g + 茶具', qr_prefix: 'DHP2024',
    is_hot: false, is_new: false,
    rating: 4.9, reviews: 342, sold_count: 168, stock: 55,
    tags: ['岩骨花香', '精品茶具套装', '商务礼品'],
    tasting_notes: '岩韵明显，兰香持久，汤色金黄透亮，岩骨之感令人回味',
    ai_pairing: ['茶点', '坚果', '清淡糕点'],
  },
  {
    id: 'biluochun-2024',
    name: '洞庭碧螺春 · 特级',
    category: 'tea', brand: '苏州茶厂',
    year: 2024, degree: 0,
    price: 380, original_price: 480,
    unit: '盒/100g', qr_prefix: 'BLC2024',
    is_hot: false, is_new: true,
    rating: 4.7, reviews: 528, sold_count: 290, stock: 120,
    tags: ['明前春茶', '特级绿茶', '花果香'],
    tasting_notes: '嫩绿鲜爽，毫香蜜韵，清甜回甘，是绿茶中的上品',
    ai_pairing: ['清淡点心', '坚果', '新鲜水果'],
  },

  // ── 雪茄 ──────────────────────────────────────────────────────
  {
    id: 'cohiba-siglo',
    name: '高希霸 世纪六号 古巴雪茄',
    category: 'cigar', brand: '高希霸',
    year: 2023, degree: 0,
    price: 1800, original_price: 2200,
    unit: '支/单支', qr_prefix: 'CHS2023',
    is_hot: true, is_new: false,
    rating: 5, reviews: 156, sold_count: 89, stock: 24,
    tags: ['古巴国宝', '至尊系列', '限量珍藏'],
    tasting_notes: '奶油、坚果与雪松香气交融，烟灰洁白细腻，燃烧均匀优雅',
    ai_pairing: ['威士忌', '干邑白兰地', '浓缩咖啡'],
  },
  {
    id: 'montecristo-4',
    name: '蒙特克里斯托 4号 古巴雪茄',
    category: 'cigar', brand: '蒙特',
    year: 2023, degree: 0,
    price: 320, original_price: 420,
    unit: '支/单支', qr_prefix: 'MC42023',
    is_hot: false, is_new: false,
    rating: 4.7, reviews: 289, sold_count: 245, stock: 60,
    tags: ['中等烟力', '均衡经典', '入门雪茄'],
    tasting_notes: '木质、坚果、咖啡的和谐组合，烟力适中，是入门古巴雪茄的理想选择',
    ai_pairing: ['干邑白兰地', '浓缩咖啡', '黑巧克力'],
  },

  // ── 礼品 ──────────────────────────────────────────────────────
  {
    id: 'gift-maotai-box',
    name: '贵州茅台节日礼盒 · 双瓶装',
    category: 'gift', brand: '茅台',
    year: 2023, degree: 53,
    price: 3200, original_price: 3800,
    unit: '盒/2×500ml', qr_prefix: 'MTGIFT',
    is_hot: false, is_new: false,
    rating: 4.9, reviews: 622, sold_count: 180, stock: 30,
    tags: ['节日礼盒', '双瓶套装', '高端送礼'],
    tasting_notes: '飞天经典酱香，双瓶装隆重正式，精美礼盒适合各种节庆场合',
    ai_pairing: ['商务宴请', '节日馈赠', '收藏投资'],
  },

  // ── 下酒菜 ────────────────────────────────────────────────────
  {
    id: 'food-hairy-crab',
    name: '阳澄湖大闸蟹 · 礼盒装',
    category: 'food', brand: '阳澄湖蟹业',
    year: 2024, degree: 0,
    price: 880, original_price: 1200,
    unit: '盒/公3.5两×4+母2.5两×4',
    qr_prefix: 'DLHC2024',
    is_hot: false, is_new: false,
    rating: 4.8, reviews: 1823, sold_count: 620, stock: 80,
    tags: ['阳澄湖', '礼盒装', '现发活蟹'],
    tasting_notes: '蟹膏饱满，鲜甜醇厚，搭配茅台享受极致秋蟹体验',
    ai_pairing: ['茅台飞天', '黄酒', '姜茶'],
  },
  {
    id: 'food-iberico-ham',
    name: '西班牙伊比利亚火腿 · 切片装',
    category: 'food', brand: 'Jamón',
    year: 2023, degree: 0,
    price: 480, original_price: 620,
    unit: '盒/100g切片装', qr_prefix: 'IBHAM',
    is_hot: false, is_new: false,
    rating: 4.7, reviews: 342, sold_count: 180, stock: 60,
    tags: ['伊比利亚猪', '72个月熟成', '配红酒最佳'],
    tasting_notes: '入口即化，坚果油脂香气绵延，是配合葡萄酒的顶级佐餐',
    ai_pairing: ['拉菲正牌', '里奥哈红酒', '曼萨尼亚雪利'],
  },
];

export const MOCK_STORES = [
  {
    id: 's1',
    name: '百邑酒世界·旗舰店',
    address: '广东省广州市天河区天河路385号太古汇B1层',
    lat: 23.1347, lng: 113.3239,
    phone: '020-8888-8888',
    hours: '10:00 - 22:00',
    rating: 4.9, distance: '0.3km', type: '旗舰店',
    tags: ['茅台专柜', '威士忌体验区', '雪茄室'],
    is_open: true,
    video_url: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 's2',
    name: '百邑酒世界·珠江新城店',
    address: '广州市天河区珠江新城华就路28号',
    lat: 23.1205, lng: 113.3246,
    phone: '020-7777-6666',
    hours: '10:30 - 21:30',
    rating: 4.7, distance: '1.2km', type: '精品店',
    tags: ['洋酒专区', '礼品定制'],
    is_open: true,
    video_url: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 's3',
    name: '百邑酒世界·番禺万达店',
    address: '广州市番禺区迎宾路万达广场3F-B区',
    lat: 22.9578, lng: 113.3542,
    phone: '020-6666-5555',
    hours: '10:00 - 22:00',
    rating: 4.6, distance: '15km', type: '标准店',
    tags: ['白酒专营'],
    is_open: false,
    video_url: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 's4',
    name: '百邑酒世界·越秀正佳店',
    address: '广州市越秀区中山五路正佳广场L4',
    lat: 23.1287, lng: 113.2895,
    phone: '020-5555-4444',
    hours: '10:00 - 21:00',
    rating: 4.8, distance: '3.5km', type: '精品店',
    tags: ['红酒体验', '进口啤酒', '茗茶'],
    is_open: true,
    video_url: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
];

export const MOCK_CARDS = {
  'BY-2024-001': { balance: 5000, total: 5000, status: 'active',  expire: '2026-12-31' },
  'BY-2024-002': { balance: 2800, total: 3000, status: 'active',  expire: '2026-06-30' },
  'BY-2024-003': { balance: 0,    total: 1000, status: 'used',    expire: '2025-12-31' },
  'BY-DEMO-888': { balance: 888,  total: 888,  status: 'active',  expire: '2027-01-01' },
  'BAIY-2024-8A3F9E': { balance: 650, total: 1000, status: 'active', expire: '2026-01-15',
    transactions: [
      { date: '2024-03-10', store: '百邑酒行·天河旗舰店', amount: -350, item: '贵州茅台×1' }
    ]
  },
};

export const MOCK_INVENTORY_STATS = {
  total_skus: 128,
  low_stock_count: 7,
  out_of_stock_count: 2,
  today_sales: 38,
  today_revenue: 62480,
  recent_scans: [
    { id: 1, sku: 'MT-2015-001', name: '茅台2015年飞天', action: 'OUT', qty: 2, time: '14:32' },
    { id: 2, sku: 'HN-XO-700',  name: '轩尼诗XO 700ml', action: 'IN',  qty: 12, time: '13:18' },
    { id: 3, sku: 'MC-18-SH',   name: '麦卡伦18年雪莉', action: 'OUT', qty: 1, time: '12:45' },
    { id: 4, sku: 'LF-ZB-2020', name: '拉菲珍宝2020',   action: 'OUT', qty: 3, time: '11:20' },
    { id: 5, sku: 'MT-2018-001', name: '茅台2018年精飞', action: 'IN',  qty: 6, time: '10:55' },
    { id: 6, sku: 'GF-15-SL',   name: '格兰菲迪15年',   action: 'IN',  qty: 4, time: '10:10' },
    { id: 7, sku: 'DS-DG-39',   name: '獭祭大吟酿39',   action: 'OUT', qty: 8, time: '09:40' },
  ],
};
